// Every primary key in the real backend is a UUID, generated by
// PostgreSQL's gen_random_uuid()/Prisma's @default(uuid()) — never a
// sequential integer (confirmed across all 8 tables in schema.prisma).
// crypto.randomUUID() produces the same v4 UUID shape and is a native
// Web Crypto API, available in Workers with no dependency and no Node
// compatibility flag needed. Step 11 explicitly requires preserving UUID
// compatibility, not introducing sequential IDs — this does exactly that.
export function newId(): string {
  return crypto.randomUUID();
}

// Every DateTime column in schema.prisma is TIMESTAMPTZ, stored in the
// D1 schema as TEXT (see migrations/0001_initial_schema.sql's header).
// Always written as a full ISO-8601 UTC string from application code —
// not left to SQLite's CURRENT_TIMESTAMP default, whose format differs
// slightly — so every stored timestamp is consistent and matches what
// the existing NestJS backend's PostgreSQL TIMESTAMPTZ columns already
// serialize to over JSON today.
export function nowIso(): string {
  return new Date().toISOString();
}

// Matches NestJS's ParseUUIDPipe gate on every :id/:propertyId/
// :attachmentId route param — a malformed id is rejected as a 400
// VALIDATION_ERROR before any database lookup, not treated as a 404.
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isValidUuid(value: string | undefined | null): value is string {
  return typeof value === 'string' && UUID_PATTERN.test(value);
}
